version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: neotravel-n8n

    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Europe/Paris
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_PROXY_HOPS=1

    volumes:
      - ./data:/home/node/.n8n

    depends_on:
      - gotenberg

    networks:
      - neotravel

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: neotravel-gotenberg

    restart: unless-stopped

    ports:
      - "3000:3000"

    networks:
      - neotravel

networks:
  neotravel:
    driver: bridge